//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginLogout.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class TBLUserInfo
    {
        public int IdUs { get; set; }

        [Required(ErrorMessage ="This field is required")]
        [Display(Name = "Username")]
        public string UsernameUs { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name ="Password")]
        [DataType(DataType.Password)]
        public string PasswrodUs { get; set; }

        [Required(ErrorMessage = "This field is required")]
        [Display(Name = "RePassword")]
        [DataType(DataType.Password)]
        [Compare("PasswrodUs",ErrorMessage ="Confirm password doesn't match, type again !")]
        public string RePasswrodUs { get; set; }
    }
}
